### PR TITLE
Add macos support

### PR DESCRIPTION
**Pull request by HenryDev**
ios and web don't work out of the box, but the app runs on macos desktop just fine.

Screenshot 2023-11-27 at 9 49 09 PM

### CODE REVIEW

**Comment by danemadsen** [comment]
Does local prompting work? The main issue in the past with new platforms has been linking the C++ code to the application correctly.

**Comment by HenryDev** [comment]
It does not. Created #163

**Comment by danemadsen** [comment]
It may just be an issue Ive introduced as I'm working on providers at the moment. Local isn't working anywhere at the moment. Ill leave this PR open for now and we will look at it again once i have the issues with providers figured out.

**Comment by danemadsen** [comment]
Ok give local gen a shot again

**Comment by HenryDev** [comment]
No that's not it. I think the issue is linking the c++ code like you said. The dynamic library is looking for 'core_init' but it's not built. It should probably be 'core.dylib' where it loads at lib/core/local_generation.dart:47, but I don't know where these files come from.

**Pull request closed without merging**
