### PR TITLE
moved at first line WidgetsFlutterBinding

### PR DESCRIPTION
**Pull request by sfiannaca**
I am experiencing the same issue that I previously reported. That's is why I added this line at the first line

Restarted application in 738ms.
E/flutter ( 5450): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Binding has not yet been initialized.
E/flutter ( 5450): The "instance" getter on the ServicesBinding binding mixin is only available once that binding has been initialized.
E/flutter ( 5450): Typically, this is done by calling "WidgetsFlutterBinding.ensureInitialized()" or "runApp()" (the latter calls the former). Typically this call is done in the "void main()" method. The "ensureInitialized" method is idempotent; calling it multiple times is not harmful. After calling that method, the "instance" getter will return the binding.
E/flutter ( 5450): In a test, one can call "TestWidgetsFlutterBinding.ensureInitialized()" as the first line in the test's "main()" method to initialize the binding.
E/flutter ( 5450): If ServicesBinding is a custom binding mixin, there must also be a custom binding class, like WidgetsFlutterBinding, but that mixes in the selected binding, and that is the class that must be constructed before using the "instance" getter.
E/flutter ( 5450): #0      BindingBase.checkInstance.<anonymous closure> (package:flutter/src/foundation/binding.dart:308:9)
E/flutter ( 5450): #1      BindingBase.checkInstance (package:flutter/src/foundation/binding.dart:389:6)
E/flutter ( 5450): #2      ServicesBinding.instance (package:flutter/src/services/binding.dart:56:54)
E/flutter ( 5450): #3      _findBinaryMessenger (package:flutter/src/services/platform_channel.dart:136:25)
E/flutter ( 5450): #4      BasicMessageChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:181:56)
E/flutter ( 5450): #5      BasicMessageChannel.send (package:flutter/src/services/platform_channel.dart:195:38)
E/flutter ( 5450): #6      SharedPreferencesApi.getAll (package:shared_preferences_android/src/messages.g.dart:227:10)
E/flutter ( 5450): #7      SharedPreferencesAndroid.getAllWithParameters (package:shared_preferences_android/shared_preferences_android.dart:99:20)
E/flutter ( 5450): #8      SharedPreferencesAndroid.getAll (package:shared_preferences_android/shared_preferences_android.dart:81:12)
E/flutter ( 5450): #9      SharedPreferences._getSharedPreferencesMap (package:shared_preferences/shared_preferences.dart:255:38)
E/flutter ( 5450): #10     SharedPreferences.getInstance (package:shared_preferences/shared_preferences.dart:78:19)
E/flutter ( 5450): #11     MemoryManager.init (package:maid/static/memory_manager.dart:19:23)
E/flutter ( 5450): #12     main (package:maid/main.dart:10:17)
E/flutter ( 5450): #13     _runMain.<anonymous closure> (dart:ui/hooks.dart:159:23)
E/flutter ( 5450): #14     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:19)
E/flutter ( 5450): #15     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
E/flutter ( 5450):
D/EGL_emulation( 5450): app_time_stats: avg=22691.62ms min=22691.62ms max=22691.62ms count=1

### CODE REVIEW

**Comment by sfiannaca** [comment]
Also I added an automatic configuration for n_threads slider. I tested only on my android device

**Comment by danemadsen** [comment]
Ive never seen this issue before? try clearing the cache if you haven't already.

**Comment by sfiannaca** [comment]
Yeah this happens on my linux too.

**Comment by sfiannaca** [comment]
I take this opportunity to report another error:

Launching lib\main.dart on Windows in debug mode...
C:\Users\Enjoy\Desktop\Dev\Maid\core\llama.cpp\ggml-quants.c(532,26): warning C4244: '=': conversione da 'float' a 'int8_t'. Possibile perdita di dati. [C:\Users\Enjoy\Desktop\Dev\Maid\build\windows\core\llama.cpp\ggml.vcxproj]
C:\Users\Enjoy\Desktop\Dev\Maid\core\llama.cpp\ggml-quants.c(750,36): warning C4244: '=': conversione da 'float' a 'int8_t'. Possibile perdita di dati. [C:\Users\Enjoy\Desktop\Dev\Maid\build\windows\core\llama.cpp\ggml.vcxproj]
C:\Users\Enjoy\Desktop\Dev\Maid\core\llama.cpp\ggml-quants.c(751,36): warning C4244: '=': conversione da 'float' a 'int8_t'. Possibile perdita di dati. [C:\Users\Enjoy\Desktop\Dev\Maid\build\windows\core\llama.cpp\ggml.vcxproj]
C:\Users\Enjoy\Desktop\Dev\Maid\core\llama.cpp\llama.cpp(1103,1): warning C4305: 'inizializzazione': troncamento da 'double' a 'float' [C:\Users\Enjoy\Desktop\Dev\Maid\build\windows\core\llama.cpp\llama.vcxproj]

this is on master branch of your llama.ccp forks (7feec2ef) i can't run debug on windows

**Comment by danemadsen** [comment]
Those are warning and they stem from llama.cpp not maid. Not something I can fix on my end. They shouldn't break windows though

**Comment by danemadsen** [comment]
ok, does that file exist in your builds asset folder?

**Comment by sfiannaca** [comment]
Yes, this error is thrown only on debug until the file is loaded, then works fine

**Pull request merged**
